import type { TimelineEvent } from './supabase';

export const DEFAULT_TIMELINE_EVENTS: Array<
  Pick<TimelineEvent, 'title' | 'description' | 'date' | 'category' | 'icon' | 'is_milestone' | 'link'>
> = [
  {
    title: '达特茅斯会议',
    description: '"人工智能"一词在达特茅斯夏季研讨会上被正式提出，AI作为一门学科由此诞生',
    date: '1956-08-01',
    category: 'industry',
    icon: '🎓',
    is_milestone: true,
    link: '',
  },
  {
    title: '深蓝战胜卡斯帕罗夫',
    description: 'IBM"深蓝"在正式比赛中击败国际象棋世界冠军卡斯帕罗夫，AI首次在智力竞技中证明实力',
    date: '1997-05-11',
    category: 'breakthrough',
    icon: '♟️',
    is_milestone: true,
    link: '',
  },
  {
    title: 'AlexNet引爆深度学习',
    description: '深度卷积神经网络在ImageNet图像识别大赛上大幅领先传统方法，开启深度学习浪潮',
    date: '2012-10-01',
    category: 'breakthrough',
    icon: '🧠',
    is_milestone: true,
    link: '',
  },
  {
    title: 'AlphaGo战胜李世石',
    description: 'DeepMind的AlphaGo以4比1击败围棋世界冠军李世石，强化学习走向公众视野',
    date: '2016-03-15',
    category: 'breakthrough',
    icon: '🎯',
    is_milestone: true,
    link: '',
  },
  {
    title: 'Transformer论文发布',
    description: '《Attention Is All You Need》提出Transformer架构，成为后续所有大语言模型的基石',
    date: '2017-06-12',
    category: 'breakthrough',
    icon: '📐',
    is_milestone: true,
    link: '',
  },
  {
    title: 'GPT-1发布',
    description: 'OpenAI推出首个生成式预训练Transformer模型，验证了"预训练+微调"的语言模型范式',
    date: '2018-06-11',
    category: 'product',
    icon: '📄',
    is_milestone: false,
    link: '',
  },
  {
    title: 'GPT-3发布',
    description: '1750亿参数的大语言模型展现出强大的少样本学习能力，"大模型"概念开始破圈',
    date: '2020-06-11',
    category: 'product',
    icon: '🌐',
    is_milestone: true,
    link: '',
  },
  {
    title: 'ChatGPT发布',
    description: 'OpenAI推出对话式产品ChatGPT，上线两个月用户破亿，AI正式走入大众生活',
    date: '2022-11-30',
    category: 'product',
    icon: '💬',
    is_milestone: true,
    link: '',
  },
  {
    title: 'GPT-4发布',
    description: '多模态理解能力大幅提升，在多项专业考试中达到接近人类专家的水平',
    date: '2023-03-14',
    category: 'product',
    icon: '🚀',
    is_milestone: true,
    link: '',
  },
  {
    title: 'Anthropic发布Claude',
    description: '主打"宪法式AI"安全理念的大模型正式登场，与OpenAI形成双雄格局',
    date: '2023-03-14',
    category: 'product',
    icon: '🤖',
    is_milestone: false,
    link: '',
  },
  {
    title: 'Sora发布',
    description: 'OpenAI公开文生视频模型Sora，展示接近真实的长视频生成能力，多模态生成进入新阶段',
    date: '2024-02-15',
    category: 'product',
    icon: '🎬',
    is_milestone: true,
    link: '',
  },
  {
    title: 'DeepSeek R1发布',
    description: '开源推理模型以极低训练成本达到顶尖水平，引发全球资本市场对AI格局的重新评估',
    date: '2025-01-20',
    category: 'industry',
    icon: '📉',
    is_milestone: true,
    link: '',
  },
  {
    title: 'Llama 4发布',
    description: 'Meta推出新一代开源多模态大模型，开源阵营持续追赶闭源前沿',
    date: '2025-04-05',
    category: 'product',
    icon: '🦙',
    is_milestone: false,
    link: '',
  },
  {
    title: 'Claude Opus 4 / Sonnet 4发布',
    description: 'Anthropic新一代模型大幅提升长任务自主执行能力，"AI Agent"开始走向实用',
    date: '2025-05-22',
    category: 'product',
    icon: '⚡',
    is_milestone: true,
    link: '',
  },
  {
    title: 'GPT-5发布',
    description: 'OpenAI推出统一推理与对话能力的新一代旗舰模型，登陆ChatGPT与API',
    date: '2025-08-07',
    category: 'product',
    icon: '✨',
    is_milestone: true,
    link: '',
  },
  {
    title: 'AI Agent元年',
    description: '智能体应用在编程、办公、科研等场景规模化落地，2025年被广泛视为AI Agent元年',
    date: '2025-09-01',
    category: 'industry',
    icon: '🤝',
    is_milestone: true,
    link: '',
  },
  {
    title: 'AlphaGenome发布',
    description: 'Google DeepMind推出基因组预测模型，AI加速生命科学基础研究',
    date: '2026-01-15',
    category: 'breakthrough',
    icon: '🧬',
    is_milestone: false,
    link: '',
  },
  {
    title: 'Claude Opus 4.8发布',
    description: 'Anthropic新模型在编程能力与诚实度上持续突破，模型迭代节奏进一步加快',
    date: '2026-05-28',
    category: 'product',
    icon: '🏆',
    is_milestone: true,
    link: '',
  },
  {
    title: 'AI行业动态追踪',
    description: '点击展开，查看每日AI行业要闻的详细记录——这里每天自动更新',
    date: '2026-06-12',
    category: 'tracking',
    icon: '📡',
    is_milestone: true,
    link: '',
  },
];
