import type { AiRechargeService, AccountService, DigitalItem } from './types';

export const aiRechargeServices: AiRechargeService[] = [
  // ── Featured ──────────────────────────────────────────────────
  {
    id: 'chatgpt-plus-turkey',
    service: 'chatgpt',
    plan: 'ChatGPT Plus 土耳其区',
    desc: '土耳其区 OpenAI 官方订阅，价格约为美区 40%，高级模型 / Thinking 图像 / Codex / 深度研究全功能无阉割。',
    priceMonthly: 68,
    originalPrice: 168,
    priceNote: '美区标准价 ¥168，节省超 60%',
    badge: '最低价',
    featured: true,
    credentialType: 'password',
    features: ['高级模型', '更多消息和上传限额', '使用 Thinking 进行高级图像创建', '扩展容量的跨聊天记忆', 'Codex 编码智能体', '更高级别的深度研究', '项目和自定义 GPT'],
  },
  // ── ChatGPT ───────────────────────────────────────────────────
  {
    id: 'chatgpt-plus-turkey-ready',
    service: 'chatgpt',
    plan: 'ChatGPT Plus 土耳其区（成品号）',
    desc: '由站长注册并激活的土耳其区 Plus 成品账号，付款后直接发送账号密码，即买即用。',
    priceMonthly: 88,
    priceNote: '即买即用 · 土耳其区低价',
    badge: '成品号',
    credentialType: 'none',
    isReadyMade: true,
    features: ['完整账号 + 密码', '高级模型', '更多消息和上传限额', 'Codex 编码智能体', '项目和自定义 GPT'],
  },
  {
    id: 'chatgpt-go',
    service: 'chatgpt',
    plan: 'ChatGPT Go（代充）',
    desc: '解锁更多功能，畅聊不停。核心模型加量，图片生成和语音模式额度提升，Session Token 代充到自有账号。',
    priceMonthly: 68,
    priceNote: '官网 $8/月，月付',
    badge: '入门',
    credentialType: 'token',
    features: ['核心模型', '更多消息和上传限额', '更多图片生成限额', '更多记忆内容', '扩展额度的语音模式'],
  },
  {
    id: 'chatgpt-plus',
    service: 'chatgpt',
    plan: 'ChatGPT Plus 美区（代充）',
    desc: '解锁全面体验。高级模型、Thinking 图像创建、Codex 编码智能体、深度研究，Session Token 代充到自有账号。',
    priceMonthly: 168,
    priceNote: '官网 $20/月，月付',
    badge: '热门',
    credentialType: 'token',
    features: ['高级模型', '更多消息和上传限额', '使用 Thinking 进行高级图像创建', '扩展容量的跨聊天记忆', 'Codex 编码智能体', '更高级别的深度研究', '项目和自定义 GPT'],
  },
  {
    id: 'chatgpt-plus-ready',
    service: 'chatgpt',
    plan: 'ChatGPT Plus 美区（成品号）',
    desc: '站长注册的美区 ChatGPT Plus 成品账号，高级模型全功能，付款后直接收到账号密码，即买即用。',
    priceMonthly: 198,
    priceNote: '热门套餐 · 即买即用',
    badge: '成品号',
    credentialType: 'none',
    isReadyMade: true,
    features: ['完整账号 + 密码', '高级模型', 'Codex 编码智能体', '更高级别的深度研究', '不需要提供自己的账号'],
  },
  {
    id: 'chatgpt-pro-5x',
    service: 'chatgpt',
    plan: 'ChatGPT Pro 5倍档（代充）',
    desc: '有效提升效率。相比 Plus 多 5 倍使用额度，Pro 前沿模型，Codex 最大访问权限，Session Token 代充。',
    priceMonthly: 840,
    priceNote: '官网 $100/月，月付',
    badge: '5倍用量',
    credentialType: 'token',
    features: ['相比 Plus 多 5 倍使用额度', 'Pro 前沿模型', '对 Codex 的最大访问权限', '最高级别的深度研究', '无限制核心聊天', '抢先体验实验性功能'],
  },
  {
    id: 'chatgpt-pro-20x',
    service: 'chatgpt',
    plan: 'ChatGPT Pro 20倍档（代充）',
    desc: '相比 Plus 多 20 倍使用额度，无限制图片生成，全面记忆和背景信息，适合重度专业用户，Session Token 代充。',
    priceMonthly: 1680,
    priceNote: '官网 $200/月，月付',
    badge: '20倍用量',
    credentialType: 'token',
    features: ['相比 Plus 多 20 倍使用额度', 'Pro 前沿模型', '无限制且较快速的图片生成', '全面的记忆和背景信息', '对 Codex 的最大访问权限', '抢先体验实验性功能'],
  },
  // ── Claude ────────────────────────────────────────────────────
  {
    id: 'claude-pro',
    service: 'claude',
    plan: 'Claude Pro（代充）',
    desc: 'Research、Code、Cowork、无限制 Projects，更多 Claude 模型，跨会话记忆，Session Token 代充到自有账号。',
    priceMonthly: 168,
    priceNote: '官网 $22/月，月付',
    badge: '热门',
    credentialType: 'token',
    features: ['更多用量', 'Claude Code（代码智能体）', 'Cowork（协作）', '无限制 Projects', 'Research 深度研究', '跨会话记忆', '更多 Claude 模型', 'Claude in Excel / Chrome'],
  },
  {
    id: 'claude-pro-ready',
    service: 'claude',
    plan: 'Claude Pro（成品号）',
    desc: '站长注册并激活的 Claude Pro 成品账号，付款后直接收到账号密码，Claude Code / Cowork / 深度研究全功能。',
    priceMonthly: 198,
    priceNote: '热门套餐 · 即买即用',
    badge: '成品号',
    credentialType: 'none',
    isReadyMade: true,
    features: ['完整账号 + 密码', '更多用量', 'Claude Code', 'Cowork', 'Research 深度研究', '不需要提供自己的账号'],
  },
  {
    id: 'claude-max',
    service: 'claude',
    plan: 'Claude Max（代充）',
    desc: '相比 Pro 5倍或 20倍用量，推荐用于 Claude Code & Cowork，更高输出限额，高峰时段优先访问，Session Token 代充。',
    priceMonthly: 840,
    priceNote: '官网 From $110/月，月付',
    badge: '5x / 20x 用量',
    credentialType: 'token',
    features: ['相比 Pro 5倍或 20倍用量', '推荐用于 Claude Code & Cowork', '更高的全任务输出限额', '抢先体验高级 Claude 功能', '高峰时段优先访问'],
  },
  {
    id: 'claude-max-ready',
    service: 'claude',
    plan: 'Claude Max（成品号）',
    desc: '站长注册并激活的 Claude Max 成品账号，相比 Pro 5倍或 20倍用量，付款后直接发送账号密码，即买即用。',
    priceMonthly: 950,
    priceNote: '高峰优先 · 即买即用',
    badge: '成品号',
    credentialType: 'none',
    isReadyMade: true,
    features: ['完整账号 + 密码', '相比 Pro 5倍或 20倍用量', '高峰时段优先访问', '更高的输出限额', '不需要提供自己的账号'],
  },
  // ── Apple ─────────────────────────────────────────────────────
  {
    id: 'apple-id-us',
    service: 'apple',
    plan: '美区 Apple ID（代注册）',
    desc: '由站长注册美区 Apple ID，付款后 24h 内发送完整账号密码，可用于 App Store 美区下载或订阅服务。',
    priceMonthly: 38,
    priceNote: '一次性服务，含账号 + 密码',
    badge: '即买即用',
    credentialType: 'none',
    isReadyMade: true,
    features: ['美区 Apple ID 完整账号', '注册邮箱 + 密码交付', 'App Store 美区可用', '付款后 24h 内交付'],
  },
];

export const PLATFORM_INITIAL: Record<AccountService['platform'], string> = {
  twitter: '𝕏', telegram: 'TG', gmail: 'G', instagram: 'IG',
};

export const accountServices: AccountService[] = [
  {
    id: 'reg-gmail',
    platform: 'gmail',
    name: 'Gmail 账号注册',
    desc: '美区 Google 账号，可用于绑定 ChatGPT、Claude 等各类国际服务，付款后发送账号密码。',
    price: 18,
    badge: '最低价',
    features: ['美区 Google 账号', 'Gmail 邮箱', '可绑定 Google Play', '付款即发账号密码'],
    delivery: '付款确认后发送账号密码',
  },
  {
    id: 'reg-twitter',
    platform: 'twitter',
    name: 'Twitter / X 账号注册',
    desc: '独立邮箱注册，可自定义用户名，完整账号权限，付款后 24 小时内发送账号密码。',
    price: 28,
    badge: '即买即用',
    features: ['独立邮箱注册', '可自定义用户名', '完整账号权限', '付款即发账号密码'],
    delivery: '付款确认后发送账号密码',
  },
  {
    id: 'reg-telegram',
    platform: 'telegram',
    name: 'Telegram 账号注册',
    desc: '独立手机号注册，可正常接收验证码，付款后 24 小时内发送账号及登录方式。',
    price: 38,
    badge: '独立手机号',
    features: ['独立手机号注册', '可接收验证码', '立即可用', '付款即发账号信息'],
    delivery: '付款确认后发送账号密码及登录方式',
  },
  {
    id: 'reg-instagram',
    platform: 'instagram',
    name: 'Instagram 账号注册',
    desc: '海外独立邮箱注册，可设置用户名和头像，付款后发送完整账号密码。',
    price: 28,
    features: ['独立邮箱注册', '可自定义用户名', '完整账号密码', '付款即发账号信息'],
    delivery: '付款确认后发送账号密码',
  },
];

export const digitalItems: DigitalItem[] = [
  {
    id: 'digital-ebook-pack',
    type: 'ebook',
    title: '精选电子书资源包',
    desc: '涵盖技术、设计、商业、文学等多类别优质电子书合集，持续更新，付款后发送网盘链接。',
    price: 29.9,
    originalPrice: 59,
    badge: '持续更新',
    includes: ['技术类电子书', '设计类资料', '商业/效率书籍', '持续补充更新'],
    delivery: '付款确认后发送网盘链接',
    tags: ['电子书', '网盘交付'],
  },
  {
    id: 'digital-video-pack',
    type: 'video',
    title: '高清影视资源',
    desc: '精选高清电影、热门剧集，无广告无限制，付款后发送网盘直链，手机电脑均可观看。',
    price: 19.9,
    badge: '高清无广告',
    includes: ['高清电影资源', '热门剧集', '无广告直链', '长期有效'],
    delivery: '付款确认后发送网盘直链',
    tags: ['影视', '高清', '网盘'],
  },
];

export const payQrConfig = {
  wechat: process.env.NEXT_PUBLIC_WECHAT_PAY_QR || '',
  alipay: process.env.NEXT_PUBLIC_ALIPAY_PAY_QR || '',
};
